# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileList.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(864, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FileList = QtWidgets.QListView(self.centralwidget)
        self.FileList.setGeometry(QtCore.QRect(-5, 30, 371, 201))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode")
        font.setPointSize(9)
        self.FileList.setFont(font)
        self.FileList.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FileList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.FileList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.FileList.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.FileList.setObjectName("FileList")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 230, 341, 22))
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 443, 361, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.labelFrq = QtWidgets.QLabel(self.centralwidget)
        self.labelFrq.setGeometry(QtCore.QRect(10, 250, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode")
        self.labelFrq.setFont(font)
        self.labelFrq.setObjectName("labelFrq")
        self.labelMsg = QtWidgets.QLabel(self.centralwidget)
        self.labelMsg.setGeometry(QtCore.QRect(10, 270, 351, 161))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode")
        font.setPointSize(9)
        self.labelMsg.setFont(font)
        self.labelMsg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelMsg.setObjectName("labelMsg")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 1, 81, 29))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.radioFile = QtWidgets.QRadioButton(self.centralwidget)
        self.radioFile.setGeometry(QtCore.QRect(180, 8, 89, 16))
        self.radioFile.setObjectName("radioFile")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -1, 51, 31))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 0, 41, 31))
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineFactor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFactor.setGeometry(QtCore.QRect(280, 1, 71, 29))
        self.lineFactor.setAlignment(QtCore.Qt.AlignCenter)
        self.lineFactor.setObjectName("lineFactor")
        self.labeF = QtWidgets.QLabel(self.centralwidget)
        self.labeF.setGeometry(QtCore.QRect(260, 0, 16, 31))
        self.labeF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labeF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labeF.setObjectName("labeF")
        self.FileList.raise_()
        self.progressBar.raise_()
        self.labelFrq.raise_()
        self.horizontalSlider.raise_()
        self.labelMsg.raise_()
        self.lineEdit.raise_()
        self.radioFile.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineFactor.raise_()
        self.labeF.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 364, 23))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionFold = QtWidgets.QAction(MainWindow)
        self.actionFold.setObjectName("actionFold")
        self.actionMergeFileTo = QtWidgets.QAction(MainWindow)
        self.actionMergeFileTo.setObjectName("actionMergeFileTo")
        self.actionMergeFileView = QtWidgets.QAction(MainWindow)
        self.actionMergeFileView.setObjectName("actionMergeFileView")
        self.menuAbout.addAction(self.actionFold)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionMergeFileTo)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionMergeFileView)
        self.menubar.addAction(self.menuAbout.menuAction())

        tabRows = 50 #systempara numbers need to display
        tabCols = 2
        self.SysParatable = QtWidgets.QTableWidget(self.centralwidget)
        self.SysParatable.setGeometry(QtCore.QRect(400, 0, 450, 460))
        self.SysParatable.setObjectName("SysParatable")
        self.SysParatable.setColumnCount(tabCols)
        self.SysParatable.setRowCount(tabRows)

        for i in range(0,tabRows):
            item = QtWidgets.QTableWidgetItem()
            self.SysParatable.setVerticalHeaderItem(i, item)

        # self.SysParatable.setCellWidget(60-1, 0, self.cmbETYPE)
        ###################################################
        item = QtWidgets.QTableWidgetItem()
        self.SysParatable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SysParatable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SysParatable.setHorizontalHeaderItem(2, item)

        self.SysParatable.horizontalHeader().setDefaultSectionSize(70)
        self.SysParatable.horizontalHeader().setMinimumSectionSize(20)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AlignDatAnalyse"))
        self.labelFrq.setText(_translate("MainWindow", "TextLabel"))
        self.labelMsg.setText(_translate("MainWindow", "TextLabel"))
        self.radioFile.setText(_translate("MainWindow", "Fileter"))
        self.label.setText(_translate("MainWindow", "Analyse\n"
"Seconds"))
        self.label_2.setText(_translate("MainWindow", "S"))
        self.labeF.setText(_translate("MainWindow", "k:"))
        self.menuAbout.setTitle(_translate("MainWindow", "文件"))
        self.actionFold.setText(_translate("MainWindow", "Select Folder"))
        self.actionMergeFileTo.setText(_translate("MainWindow", "MergeFileTo"))
        self.actionMergeFileView.setText(_translate("MainWindow", "MergeFileView"))

        
    
    def setVerTitle(self, index, verStr):
        _translate = QtCore.QCoreApplication.translate
        item = self.SysParatable.verticalHeaderItem(index)
        item.setText(_translate("MainWindow", verStr))

    
    def setRowTitle(self, index, verStr):
        _translate = QtCore.QCoreApplication.translate
        item = self.SysParatable.horizontalHeaderItem(index)
        item.setText(_translate("MainWindow", verStr))

    def resetSize(self, col, row):
        self.SysParatable.setColumnCount(col)
        self.SysParatable.setRowCount(row)
        for i in range(0,row):
            item = QtWidgets.QTableWidgetItem()
            self.SysParatable.setVerticalHeaderItem(i, item)
        for i in range(0,col):
            item = QtWidgets.QTableWidgetItem()
            self.SysParatable.setHorizontalHeaderItem(i, item)

    def setCellValue(self,col,row,value):
        self.SysParatable.setItem(col, row, QtWidgets.QTableWidgetItem(str(value)))

